name: terragrunt-atlantis-config
on:
  push:
    paths:
    - '**.hcl'
    - '**.tf'
    - '**.hcl.json'

jobs:
  terragrunt_atlantis_config:
    runs-on: ubuntu-latest
    name: Validate atlantis.yaml
    steps:
      - uses: actions/checkout@v2
      - name: Ensure atlantis.yaml is up to date using terragrunt-atlantis-config
        id: atlantis_validator
        uses: transcend-io/terragrunt-atlantis-config-github-action@v0.0.3
        with:
          version: v1.16.0
          extra_args: '--autoplan --parallel=false