name: Renovate Dependency Check

on: [push, pull_request]

jobs:
  renovate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        npm install -g renovate

    - name: Run Renovate
      run: |
        renovate --platform=github --token=${{ secrets.GITHUB_TOKEN }}